{English GUI}

resourcestring

  capForm='Update EXIF data of JPG files from CGO3+';
  capScan='Scan';
  hntScan='Scan pictures and add EXIF data from FlightLog';
  capClose='Close';
  capBackup='Update copies';
  hntBackup='Keep original picture files untouched and update copies';
  capVariance='Variance';
  hntDelta='Maximum delta position in cm between EXIF and FlightLog coordinates';
  capLogs='Telemetry';                             {Open a telemetry file}
  hntLogs='Select Telemetry file from related FlightLog';
  capPics='Pictures';                              {Select folder for pictures}
  hntPics='Select directory with JPG files from CGO3+';
  capOpenDialog='Select telemetry file...';
  capTextDialog='Load text file...';
  capDirDialog='Select picture folder...';
  capSaveTab='Save table as...';
  capController='Controller role';
  capSaveCSV='Save table as CSV';
  capLog='Create log file';
  hntLog='Create log file in CSV format in the project folder';
  capGeoid='Geoid undulation';
  hntGeoid='Correction value from Ellipsoid to Geoid [m]; double click to call "GeoidEval"';
  capSettings='Settings';
  capMain='Protocol';
  capEXIF='EXIF data handling';
  capFiles='File handling';
  capUpdateAlt='Update altitude';
  hntUpdateAlt='Correct altitude to absolute altitude instead of reltive altitude';
  capJSON='Create JSON';
  hntJSON='Create additional JSON files per picure file';
  capEXIFwrite='Update EXIF';
  hntEXIFwrite='Enable writing EXIF data into the picture file';
  capCorrAlt='Geoid calculation';
  capAutoGeoid='Obtain from internet';
  hntAutoGeoid='Obtain correction value automatically from web tool GeoidEval';
  capGravity='Gravity model';
  hntGravity='Select preferred gravity model for correction value';
  capGitHub='GitHub repository';
  capManual='User manual';

  capKeepComment='Keep original UserComment';
  hntKeepComment='Keep original user comment in EXIF as part of UserComment';
  hntMemo='Text with additional info in EXIF as part of UserComment';
  capSetInfo='AdditionalText allowed';
  hntSetInfo='Add free text to UserComment in EXIF meta data';
  capLoad='Load from text file';
  capPaste='Paste';
  capClear='Clear text';

  rsHeader='File name,Date/time,EXIF version,Coordinates,Variance,Altitude,Telemetry match,'+
           'Remote,RemoteGPS,Model,XMP,Additional text,Updated';
  rsLogHeader='File name,File date,EXIF date,Type,Sequence No,Variance [cm],'+
              'Latitude,Longitude,Altitude [m],Ascent [m],Distance [m],Bearing [°]';

  rsNo='no';
  rsYes='done';

  rsExtFilter='CSV files (default)|*.csv|Text files|*.txt|All files|*.*';
  rsNoFiles='No picture files found';
  rsNoFlight='Take off not detected';
  rsMissLog='Missing FlightLog';
  rssavedTo='Saved to';
  rsfailDir='Failed to create folder';

  rgitem0='Single mode';
  rgitem1='Team mode main';
  rgitem2='Team mode camera';
  rgitem3='Wizard';
  rgitem4='Self-defined';

